### ISSUE TITLE
Fix travis matrix

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_coursebank#14]
Travis file is need to be updated to match correct PHP versions to different moodle versions.

**Comment by danmarsden** [comment]
pushed a fix to use v2 of the plugin-ci and added config to use travis build stages so that only behat/unit tests are run on all builds, and the other moodle checks are only run on a single build. - took a bit to get the config right but seems to be working ok now.

I did end up disabled the copy/paste check because it detects some minor duplication in rendered.php but generates an "error" state and prevents the build stage from continuing to unit/behat testing.
